### PR TITLE
Middle section web mobile

### PR DESCRIPTION
**Pull request by aizjicod**
in this part of the project, it was added the section "my recent works", it was stylized later on after it was structured in HTML.
Then I proceeded to work on the "skill" section and as before it was stylized later on after it was structured in HTML.

### CODE REVIEW

**Review by KayLemba — APPROVED** [review]
Hi @aizjicod ,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

To Highlight 💯
No linters errors ✔️
Descriptive commit messages ✔️

**Optional suggestions**
This is an example of how you write a Pull request.
Example:
Title: Mobile Portfolio
- Update index.html file
- Update style.css file
- Add README.md file
etc... 
Avoid writing paragraphs  in your pull request section for they are not descriptive I hope to see some improvements soon, Thanks
Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by aizjicod** [comment]
thanks you sooo much!!!

**Comment by aizjicod** [comment]
on the next project, I will do as you say thank you so much @KayLemba

**Comment by KayLemba** [comment]
You are welcome.

**Pull request merged**
